### ISSUE TITLE
[BO - Profil utilisateur] Gérer son compte utilisateur

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#108]
Ajout pour les utilisateurs d'une page de gestion de leur compte.
Ressources : 
- [Spéficications](https://github.com/MTES-MCT/histologe/wiki/Gerer-le-profil)
- [Prototype](https://xd.adobe.com/view/16386013-8dac-45bf-ad9e-760d94c1612a-436b/screen/3cc7be23-f308-4e32-a66c-62124a3af09a/)

Tâches : 
- [x] Créer la page profil
- [x] Ajouter avatar sur le dashboard
- [x] Ajouter avatar + modifier menu BO
- [x] MTES-MCT/histologe#107 
- [x] MTES-MCT/histologe#105 
- [x] MTES-MCT/histologe#2932
- [x] MTES-MCT/histologe#104

**Comment by hmeneuvrier** [comment]
TODO : 
- tests
- avatar -dashboard
- gestion erreur password à vérifier
