### ISSUE TITLE
[FO - Page suivi usager] Revoir l'UI V2

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#2578]
Cette V2 comprend : 
- [x] Ajout de la suppression des docs et photos -> ✅ déjà fait #3521 
- [ ] Ajout feature exporter mon signalement (PDF) -> #3982 
- [ ] [FO - Suivi usager] Tableau de bord usager -> #4069 
- [ ] [FO - Suivi usager] Page d'info du signalement -> #4070
- [ ] [FO - Suivi usager] Page messagerie -> #4071
- [ ] [FO - Suivi usager] Page photos et documents -> #4072
- [ ] Ajout feature annuler mon signalement -> #3980 

--------------------

## Contexte
Besoins : 
- Avoir un espace suivi plus compréhensible par les usagers
- Avoir des actions clairement définies
- Permettre l'évolution vers de nouvelles actions usagers (cf. #2577 )

Solution : 
Revoir l'architecture et l'UI de l'espace suivi de l'usager.

### Ressources 
- [Le prototype mobile](https://xd.adobe.com/view/04e0afaf-73a5-4263-96f2-76b605dc0cd7-51b3/) est dispo en ligne
- [Le mode specs](https://xd.adobe.com/view/04e0afaf-73a5-4263-96f2-76b605dc0cd7-51b3/specs/) permet de récupérer le texte
⚠ Les textes d'intro ou de description peuvent différer des textes actuels. Je vous conseille de prendre les textes présents dans la le prototype !
- [Le prototype desktop](https://xd.adobe.com/view/e5dc844d-e2df-4a71-9d12-fc28d810f0bb-b08f/) est également dispo
- Les pictos du DSFR utilisés pour les tuiles sont dispo [sur le drive](https://drive.google.com/drive/u/0/folders/1BslUuR9XSB_V0FycCxTGj5EdLJ5lzAlU)

**Aperçu de la navigation**
https://github.com/user-attachments/assets/96482363-cd34-41f4-b66b-bef44b643979

**Comment by mathildepoulpux** [comment]
## Contexte
Besoins : 
- Avoir un espace suivi plus compréhensible par les usagers
- Avoir des actions clairement définies
- Permettre l'évolution vers de nouvelles actions usagers (cf. #2577 )

Solution : 
Revoir l'architecture et l'UI de l'espace suivi de l'usager.

### Ressources 
- [Le prototype](https://xd.adobe.com/view/b1166e7d-53f1-4156-b5b2-efd505ab3cc5-e445/) est dispo en ligne
- [Le mode specs](https://xd.adobe.com/view/b1166e7d-53f1-4156-b5b2-efd505ab3cc5-e445/specs/) permet de récupérer le texte
⚠ Les textes d'intro ou de description peuvent différer des textes actuels. Je vous conseille de prendre les textes présents dans la le prototype !
- Les pictos du DSFR utilisés pour les tuiles sont dispo [sur le drive](https://drive.google.com/drive/u/0/folders/1BslUuR9XSB_V0FycCxTGj5EdLJ5lzAlU)

**Aperçu de la navigation**
https://github.com/user-attachments/assets/96482363-cd34-41f4-b66b-bef44b643979

## L'espace suivi
Le principe de base est de créer des pages distinctes 
- Accueil
- Messagerie 
- Détails du dossier
- Pièces du dossier (= photos et doc)

Cette nouvelle architecture permet une nouvelle organisation de l'information, qui se base sur les données existantes.

### [Accueil 🔗 ](https://xd.adobe.com/view/b1166e7d-53f1-4156-b5b2-efd505ab3cc5-e445/)
La page d'accueil est séparée en différentes sections : 
- **Votre dossier** comprend une carte qui est un peu la carte d'identité du dossier, avec les infos suivantes : 
    - Nom prénom du déclarant 
    - Nom prénom de l'occupant du logement (si signalement fait par l'occupant, on ne l'affiche pas)
    - Référence du dossier
    - Statut du dossier 
- Un **accès rapide** comprenant : 
    - Une tuile contenant la dernière nouveauté sur le dossier -> cette tuile n'est pas affichée s'il n'y a pas de nouveauté et on en affiche qu'une seule (donc l'évènement le plus récent) (-> plus de détails après cette liste)
    - Un bouton d'accès à la page Messagerie 
    - Un bouton d'accès à la page Détails du dossier
    -  Un bouton d'accès à la page Pièces du dossier
    -  Un bouton d'action pour demander l'arrêt de la procédure
- Un call-out `Prévenez le propriétaire` -> affiché si la réponse à "Propriétaire averti ?" est Non ou NSP
- Une section de texte **Infos utiles** avec des liens vers des pages et articles utiles pour l'usager

#### La tuile nouveauté
C'est une tuile horizontale, taille SM (voir le [DSFR](https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/tuile)), composée de : 
- d'un titre
- un label
- un picto (ils sont dispo [sur le drive](https://drive.google.com/drive/u/0/folders/1BslUuR9XSB_V0FycCxTGj5EdLJ5lzAlU))
- un détail -> la date de l'évènement

![Image](https://github.com/user-attachments/assets/0c1f53b6-8d2d-4b20-9b1f-58d8efba43d3)

La tuile renvoie toujours vers le dernier suivi en date.
Pour autant, il faudrait différencier ce qui est affiché dans la tuile en fonction du type de suivi : 
- **Suivi auto demande de pièces**
   - label : `A faire` couleur info
   - titre : Demande de documents
   - picto : document-add (dossier documents)
- **Suivi auto signalement validé**
   - Label : `Nouveauté` couleur success
   - titre : Votre dossier est validé
   - picto : success (dossier system) 
- **Suivi auto affectation acceptée**
   - Label : `Nouveauté` couleur success
   - titre : Votre dossier est pris en charge 
   - picto : success (dossier system) 
- **Suivi nouveaux documents**
   - label : `Nouveauté` couleur info
   - titre : Nouveaux documents disponibles
   - picto : document (dossier documents)
- **Visite programmée**
   - label : `Nouveauté` couleur success
   - titre :  Visite du logement programmée
   - picto : house (dossier buildings)
- **Visite annulée**
   - label : `Important` couleur error
   - Titre : Visite annulée
   - picto : error (dossier system)
- **Conclusion de visite dispo**
   - Label : `Nouveauté` couleur success
   - Titre : Conclusion de visite disponible
   - picto : conclusion (dossier documents)
- **Relance usager automatique** 
   - label : `A faire`
   - titre : Mettez votre situation à jour
   - picto : notification (dossier system)
- **Clôture du signalement**
   - label : `Important` couleur error
   - Titre : Fermeture de votre dossier
   - picto :  conclusion (dossier documents)
- **Autre nouveau suivi (voir maquette)**
   - label : `Nouveau message` orange
   - titre :  début du message tronqué (1 ligne)
   - picto : mail-send (dossier digital)
 

### [Messagerie 🔗 ](https://xd.adobe.com/view/b1166e7d-53f1-4156-b5b2-efd505ab3cc5-e445/screen/89aa765c-8541-4b4f-9875-548b27b535d6/)
La messagerie comprend les sections : 
- **carte d'identité du dossier** avec un lien simple permettant d'accéder à la page Détails du dossier
- Le **formulaire d'envoi de message** : il est similaire au formulaire actuel. La seule différence est que le composant du message d'info change pour le format [Notice](https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/bandeau-d-information-importante) fermable
- La partie **Suivre les échanges** qui est l'historique des suivis actuels avec les modifications suivantes : 
   - La date d'enregistrement du signalement apparaît ici plutôt qu'avant le formulaire d'envoi de message
   - S'il y a un message non lu, on lui ajoute un badge _Nouveau message_ et on passe le fond en orange avec une bordure

### [Détails du dossier 🔗 ](https://xd.adobe.com/view/b1166e7d-53f1-4156-b5b2-efd505ab3cc5-e445/screen/012c8193-b4e9-4d2d-8699-1016c24acbd5/)
La page détails du dossier comprend les sections : 
- **carte d'identité du dossier**
- Un quick access **Que voulez-vous faire** avec les boutons : 
    - Accès aux pièces du dossier
    - Téléchargement du PDF (cf. #3982 )
- Une section **Le signalement** qui reprend les infos du signalement -> sur toute cette partie, on reprend les infos actuelles mais on ne les met plus dans des accordéons. On change également l'ordre d'affichage des infos et certains titres de parties. Le nouvel ordre est : 
   - Désordres
   - Commentaire -> dans un cadre bleu
   - Coordonnées -> rassemble l'adresse du logement, les coordonnées de l'occupant et du tiers
   - Votre bailleur -> rassemble les coordonnées du bailleur + les questions de la partie actuelle "procédures et démarches" qui concernent le bailleur + le callout **Prévenez votre bailleur** si concerné, avec le fond caramel cette fois-ci
   - Informations générales sur le logement -> idem que actuel
   - Type et composition du logement -> idem que actuel
   - Situation du foyer -> idem que actuel + la question `Si des travaux sont faits, voulez-vous rester dans le logement ?` qui est aujourd'hui dans la partie Procédures et démarches
   - Votre assurance -> reprend les questions concernant l'assurance qui sont actuellement dans "procédures et démarches" + un message d'info si assurance contactée Non ou NSP + un message warning si le logement n'a pas d'assurance (le même que dans le formulaire)

### [Les pièces du dossier 🔗 ](https://xd.adobe.com/view/b1166e7d-53f1-4156-b5b2-efd505ab3cc5-e445/screen/ed20dcca-87b6-4d27-a9aa-34017fc4b4ff/)
Sur cette page, il s'agit surtout d'une amélioration de l'UI. 
La page pièces du dossier comprend les sections : 
- **carte d'identité du dossier**
- **Les documents du dossier** avec : 
    - Le bouton d'ajout de documents qui ouvre la modale correspondante
    - La liste des documents sous forme de carte avec 2 boutons : un bouton primaire pour l'afficher dans un nouvel onglet + un bouton secondaire pour le supprimer
- **Les photos du dossier** avec : 
    - Le bouton d'ajout de photos qui ouvre la modale correspondante
    - La liste des photos sous forme d'aperçu en grille avec 2 boutons : afficher / supprimer
    - Les explications pour bien prendre ses photos
    - Les rappels réglementaires sur la prise et le partage de photos 

| Interface actuelle | Nouvelle UI
| :---: | :---:
| ![Image](https://github.com/user-attachments/assets/0bda5484-998a-41c6-8f04-8387d1d3cde6) | ![Image](https://github.com/user-attachments/assets/ecb0f12f-b92d-4621-b3bf-01b046397d63)
| ![Image](https://github.com/user-attachments/assets/65f693e5-75ad-4f2e-bfd6-4126a00f6cb0) | ![Image](https://github.com/user-attachments/assets/d48dae7b-67cd-463d-bf0d-38fd0da2f3cc)
