### ISSUE TITLE
[Technique] [Sécurité] Contrôle des entrées de formulaire

### ISSUE THREAD

**Issue by numew** [MTES-MCT/histologe#2646]
![Screenshot 2024-06-03 at 17-01-57 2023_Apilos_Tests_Intrusion pdf](https://github.com/MTES-MCT/histologe/assets/7130780/7d417177-d5d2-4648-a71d-3cd5712c35f0)
Vérifier que les entrée de formulaire sont bien contrôlé coté serveur
Vérifier que sur les champs fermés de type select, checkbox radio button seul les valeurs attendu sont accepté 

Pour amoindrir le chantier, on divise en 4 tickets

- [ ] FO - Formulaire Signalement #2738
- [x] FO - Autres (fiche usager, accueil, contact) #2739
- [x] BO - Formulaires Fiche Signalement #2740
- [ ] BO - Autres (partenaires, administration) #2741
