### ISSUE TITLE
[BO - Tableau de bord] Créer des tableaux de bord par rôle

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#785]
Tâches : 
- [x] Spécifier les tableaux de bord / rôle -> Cf [réflexion sur Miro](https://miro.com/app/board/uXjVPz_L8i4=/)
- [x] [Maquettes](https://xd.adobe.com/view/788436dd-5c75-46d0-a1b8-790f1a120e29-2dd7/)
- [x] Ajouter partie ESABORA pour Super Admin
- [x] Dashboard agent & admin partenaire
- [x] Dashboard responsable territoire
- [x] Dashboard super admin
- [ ] Déplacer les filtres territoires / commune & statuts dans la page listing signalements
- [x] Modifier les URL du BO cf. [ce tableau](https://docs.google.com/spreadsheets/d/1Z2rzfxRd_jI8gTm43b-VZQ56fdtgXBDQ-JFYGmfIYfI/edit#gid=0)
- [x] Retirer le nom de l'usager et la mention "tableau de bord" sous le logo dans le menu. La remplacer par le nom du partenaire / du territoire ou la mention "Super Admin" en fonction du rôle
- [x] Créer l'indicateur nb suivi moy. / signalement  #840 
- [x] Créer l'indicateur nb suivi usager moy. / signalement
- [x] Corriger le filtre date dernier suivi cf. #743 
- [x] Identifier les types de suivi cf. #867 
- [x] Créer un filtre clôture partenaire cf. #869 

NB : cette story rendra obsolète le ticket #626

**Comment by mathildepoulpux** [comment]
Les specs : 
- [Agent](https://github.com/MTES-MCT/histologe/wiki/Dashboards#tableau-de-bord-agent)
- [Admin partenaire](https://github.com/MTES-MCT/histologe/wiki/Dashboards#tableau-de-bord-admin-partenaire)
- [Responsable territoire](https://github.com/MTES-MCT/histologe/wiki/Dashboards#tableau-de-bord-responsable-territoire)
- [Super Admin](https://github.com/MTES-MCT/histologe/wiki/Dashboards#tableau-de-bord-super-admin)
- Voir [la maquette](https://xd.adobe.com/view/788436dd-5c75-46d0-a1b8-790f1a120e29-2dd7/)

**Comment by emilschn** [comment]
Les super admin n'ont pas besoin de suivre le nombre de suivis créés ? pour le suivi des OKR notamment

**Comment by mathildepoulpux** [comment]
Le nombre total tu veux dire ?

**Comment by emilschn** [comment]
Super, merci ! :)

**Comment by sfinx13** [comment]
@mathildepoulpux @arnaudchouk Y'a t'il une période à prendre en compte sur les données du tableau de bord ? A partir de janvier 2022 ou pas ? Doit on prendre en compte les signalements importés ?

**Comment by arnaudchouk** [comment]
est ce qu il ne serait pas possible de proposer la possibilité à chaque utilisateur de sélectionner la période 
Sur les signalements importés :
pour les RT s'ils sont ouverts (sans affectation en cours ou avec) alors il faudrait leur laisser
pour les agents, importés ou non, s'ils sont affectés il faudrait les intégrer

**Comment by mathildepoulpux** [comment]
Je dirais non pour la sélection de période dans un premier temps, faut faire au plus simple. 
Donc on comptabilise sur le total. 

Ca donnerait : 
- Pour les signalements : on prend le total des signalements qui concernent le user en question (en fonction de son rôle).
    - Agent / admin partenaire -> Tous les signalements affectés à son partenaire
    - Responsable territoire -> tous ceux du territoire
    - SA -> Tout
    - A exclure : signalement supprimés

- Pour les suivis : même règles + on exclut les signalements importés pour pas fausser les stats.

- Pour les comptes : on exclut les users archivés

**Comment by arnaudchouk** [comment]
pas clair

**Comment by sfinx13** [comment]
> Accès : listing des signalements filtré sur ceux ayant eu un au moins un suivi non-automatique (saisi par un partenaire ou l'usager) depuis la dernière visite sur le suivi

Difficile à identifier, ça demande une qualification dans un premier temps si le suivi est automatique ou non

**Comment by sfinx13** [comment]
Ce filtre n'existe pas création d'un nouveau ticket #869 
## Tableau de bord Super Admin
> Clôtures partenaires :
Accès : listing des signalements filtré sur les signalements ayant été fermé par au moins 1 partenaire

**Comment by mathildepoulpux** [comment]
> pas clair

T'as pas compris quoi ?

**Comment by arnaudchouk** [comment]
a priori t as respecifié depuis ma reponse
c etait surtout la difference de prise en compte sur les signalements importés qui m interrogeait - mais on est ok on se base sur tout ce qui est ouvert

**Comment by sfinx13** [comment]
Cette tache Modifier les URL du BO est en prod j'ai crée ce ticket https://github.com/MTES-MCT/histologe/issues/980
